vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        document:
            uri_prefix: /images/document
            upload_destination: '%kernel.project_dir%/public/images/document'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        recu:
            uri_prefix: /images/recu
            upload_destination: '%kernel.project_dir%/public/images/recu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
