vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       recu:
           uri_prefix: /images/recu
           upload_destination: '%kernel.project_dir%/public/images/recu'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           

            
